name: Deploy Vue App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and build
        run: |
          npm install
          npm run build
          touch dist/.nojekyll

      - name: Deploy files to root
        run: |
          # Copy built files to root
          cp -r dist/* .
          rm -rf dist
          
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy Vue app" || echo "No changes to commit"
          git push origin main